/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: ISC
 */

#ifndef _HMSPPE_UNIPHY_REG_H_
#define _HMSPPE_UNIPHY_REG_H_

/*
 * ========================================
 * UNIPHY0 (QP_UNIPHY) Registers
 * ========================================
 */

/*[register] QP_USXG_RESET - 0x630*/
#define QP_USXG_RESET
#define QP_USXG_RESET_ADDRESS 0x630
#define QP_USXG_RESET_NUM     3
#define QP_USXG_RESET_INC     0x1
#define QP_USXG_RESET_TYPE    REG_TYPE_RW
#define QP_USXG_RESET_DEFAULT 0x7F
	/*[field] MMD1_REG_XPCS_ENABLE*/
	#define QP_USXG_RESET_MMD1_REG_XPCS_ENABLE
	#define QP_USXG_RESET_MMD1_REG_XPCS_ENABLE_OFFSET  6
	#define QP_USXG_RESET_MMD1_REG_XPCS_ENABLE_LEN     1
	#define QP_USXG_RESET_MMD1_REG_XPCS_ENABLE_DEFAULT 0x1
	/*[field] MMD1_REG_QSGMII_ENABLE*/
	#define QP_USXG_RESET_MMD1_REG_QSGMII_ENABLE
	#define QP_USXG_RESET_MMD1_REG_QSGMII_ENABLE_OFFSET  5
	#define QP_USXG_RESET_MMD1_REG_QSGMII_ENABLE_LEN     1
	#define QP_USXG_RESET_MMD1_REG_QSGMII_ENABLE_DEFAULT 0x1
	/*[field] MMD1_REG_PQSGMII_FUNC_RST_N*/
	#define QP_USXG_RESET_MMD1_REG_PQSGMII_FUNC_RST_N
	#define QP_USXG_RESET_MMD1_REG_PQSGMII_FUNC_RST_N_OFFSET  4
	#define QP_USXG_RESET_MMD1_REG_PQSGMII_FUNC_RST_N_LEN     1
	#define QP_USXG_RESET_MMD1_REG_PQSGMII_FUNC_RST_N_DEFAULT 0x1
	/*[field] MMD1_REG_USXG_FUNC_RST_N_P3*/
	#define QP_USXG_RESET_MMD1_REG_USXG_FUNC_RST_N_P3
	#define QP_USXG_RESET_MMD1_REG_USXG_FUNC_RST_N_P3_OFFSET  3
	#define QP_USXG_RESET_MMD1_REG_USXG_FUNC_RST_N_P3_LEN     1
	#define QP_USXG_RESET_MMD1_REG_USXG_FUNC_RST_N_P3_DEFAULT 0x1
	/*[field] MMD1_REG_USXG_FUNC_RST_N_P2*/
	#define QP_USXG_RESET_MMD1_REG_USXG_FUNC_RST_N_P2
	#define QP_USXG_RESET_MMD1_REG_USXG_FUNC_RST_N_P2_OFFSET  2
	#define QP_USXG_RESET_MMD1_REG_USXG_FUNC_RST_N_P2_LEN     1
	#define QP_USXG_RESET_MMD1_REG_USXG_FUNC_RST_N_P2_DEFAULT 0x1
	/*[field] MMD1_REG_USXG_FUNC_RST_N_P1*/
	#define QP_USXG_RESET_MMD1_REG_USXG_FUNC_RST_N_P1
	#define QP_USXG_RESET_MMD1_REG_USXG_FUNC_RST_N_P1_OFFSET  1
	#define QP_USXG_RESET_MMD1_REG_USXG_FUNC_RST_N_P1_LEN     1
	#define QP_USXG_RESET_MMD1_REG_USXG_FUNC_RST_N_P1_DEFAULT 0x1
	/*[field] MMD1_REG_USXG_FUNC_RST_N*/
	#define QP_USXG_RESET_MMD1_REG_USXG_FUNC_RST_N
	#define QP_USXG_RESET_MMD1_REG_USXG_FUNC_RST_N_OFFSET  0
	#define QP_USXG_RESET_MMD1_REG_USXG_FUNC_RST_N_LEN     1
	#define QP_USXG_RESET_MMD1_REG_USXG_FUNC_RST_N_DEFAULT 0x1

struct qp_usxg_reset {
	a_uint32_t  mmd1_reg_usxg_func_rst_n:1;
	a_uint32_t  mmd1_reg_usxg_func_rst_n_p1:1;
	a_uint32_t  mmd1_reg_usxg_func_rst_n_p2:1;
	a_uint32_t  mmd1_reg_usxg_func_rst_n_p3:1;
	a_uint32_t  mmd1_reg_pqsgmii_func_rst_n:1;
	a_uint32_t  mmd1_reg_qsgmii_enable:1;
	a_uint32_t  mmd1_reg_xpcs_enable:1;
	a_uint32_t  _reserved0:25;
};

union qp_usxg_reset_u {
	a_uint32_t val;
	struct qp_usxg_reset bf;
};

/*
 * ========================================
 * UNIPHY1 Registers
 * ========================================
 */

/*[register] CLOCK_GATE_ENABLE - 0x5A4*/
#define CLOCK_GATE_ENABLE
#define CLOCK_GATE_ENABLE_ADDRESS 0x5A4
#define CLOCK_GATE_ENABLE_NUM     3
#define CLOCK_GATE_ENABLE_INC     0x1
#define CLOCK_GATE_ENABLE_TYPE    REG_TYPE_RW
#define CLOCK_GATE_ENABLE_DEFAULT 0x3
	/*[field] MMD1_REG_XPCS_ENABLE*/
	#define CLOCK_GATE_ENABLE_MMD1_REG_XPCS_ENABLE
	#define CLOCK_GATE_ENABLE_MMD1_REG_XPCS_ENABLE_OFFSET  1
	#define CLOCK_GATE_ENABLE_MMD1_REG_XPCS_ENABLE_LEN     1
	#define CLOCK_GATE_ENABLE_MMD1_REG_XPCS_ENABLE_DEFAULT 0x1
	/*[field] MMD1_REG_QSGMII_ENABLE*/
	#define CLOCK_GATE_ENABLE_MMD1_REG_QSGMII_ENABLE
	#define CLOCK_GATE_ENABLE_MMD1_REG_QSGMII_ENABLE_OFFSET  0
	#define CLOCK_GATE_ENABLE_MMD1_REG_QSGMII_ENABLE_LEN     1
	#define CLOCK_GATE_ENABLE_MMD1_REG_QSGMII_ENABLE_DEFAULT 0x1

struct clock_gate_enable {
	a_uint32_t  mmd1_reg_qsgmii_enable:1;
	a_uint32_t  mmd1_reg_xpcs_enable:1;
	a_uint32_t  _reserved0:30;
};

union clock_gate_enable_u {
	a_uint32_t val;
	struct clock_gate_enable bf;
};

/*
 * ========================================
 * UNIPHY2 (PON_UNIPHY) Registers
 * ========================================
 */

/*[register] PON_SMCBC_CTRL - 0x59C*/
#define PON_SMCBC_CTRL
#define PON_SMCBC_CTRL_ADDRESS 0x59C
#define PON_SMCBC_CTRL_NUM     3
#define PON_SMCBC_CTRL_INC     0x1
#define PON_SMCBC_CTRL_TYPE    REG_TYPE_RW
#define PON_SMCBC_CTRL_DEFAULT 0x7B
	/*[field] MMD1_REG_ASYNC_SW_CLK_EN_PON_SDRX_SMCBC*/
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_SW_CLK_EN_PON_SDRX_SMCBC
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_SW_CLK_EN_PON_SDRX_SMCBC_OFFSET  6
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_SW_CLK_EN_PON_SDRX_SMCBC_LEN     1
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_SW_CLK_EN_PON_SDRX_SMCBC_DEFAULT 0x1
	/*[field] MMD1_REG_UPHY_PON_RX_SW_RSTN*/
	#define PON_SMCBC_CTRL_MMD1_REG_UPHY_PON_RX_SW_RSTN
	#define PON_SMCBC_CTRL_MMD1_REG_UPHY_PON_RX_SW_RSTN_OFFSET  5
	#define PON_SMCBC_CTRL_MMD1_REG_UPHY_PON_RX_SW_RSTN_LEN     1
	#define PON_SMCBC_CTRL_MMD1_REG_UPHY_PON_RX_SW_RSTN_DEFAULT 0x1
	/*[field] MMD1_REG_UPHY_PON_TX_SW_RSTN*/
	#define PON_SMCBC_CTRL_MMD1_REG_UPHY_PON_TX_SW_RSTN
	#define PON_SMCBC_CTRL_MMD1_REG_UPHY_PON_TX_SW_RSTN_OFFSET  4
	#define PON_SMCBC_CTRL_MMD1_REG_UPHY_PON_TX_SW_RSTN_LEN     1
	#define PON_SMCBC_CTRL_MMD1_REG_UPHY_PON_TX_SW_RSTN_DEFAULT 0x1
	/*[field] MMD1_REG_ASYNC_SW_CLK_EN_PON_SDTX_SMCBC*/
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_SW_CLK_EN_PON_SDTX_SMCBC
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_SW_CLK_EN_PON_SDTX_SMCBC_OFFSET  3
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_SW_CLK_EN_PON_SDTX_SMCBC_LEN     1
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_SW_CLK_EN_PON_SDTX_SMCBC_DEFAULT 0x1
	/*[field] MMD1_REG_ASYNC_SW_CLK_EN_GPON_SMCBC*/
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_SW_CLK_EN_GPON_SMCBC
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_SW_CLK_EN_GPON_SMCBC_OFFSET  2
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_SW_CLK_EN_GPON_SMCBC_LEN     1
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_SW_CLK_EN_GPON_SMCBC_DEFAULT 0x0
	/*[field] MMD1_REG_ASYNC_SW_CLK_EN_XGPON_SMCBC*/
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_SW_CLK_EN_XGPON_SMCBC
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_SW_CLK_EN_XGPON_SMCBC_OFFSET  1
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_SW_CLK_EN_XGPON_SMCBC_LEN     1
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_SW_CLK_EN_XGPON_SMCBC_DEFAULT 0x1
	/*[field] MMD1_REG_ASYNC_CLK_DIS_OVERRIDE_SMCBC*/
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_CLK_DIS_OVERRIDE_SMCBC
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_CLK_DIS_OVERRIDE_SMCBC_OFFSET  0
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_CLK_DIS_OVERRIDE_SMCBC_LEN     1
	#define PON_SMCBC_CTRL_MMD1_REG_ASYNC_CLK_DIS_OVERRIDE_SMCBC_DEFAULT 0x1

struct pon_smcbc_ctrl {
	a_uint32_t  mmd1_reg_async_clk_dis_override_smcbc:1;
	a_uint32_t  mmd1_reg_async_sw_clk_en_xgpon_smcbc:1;
	a_uint32_t  mmd1_reg_async_sw_clk_en_gpon_smcbc:1;
	a_uint32_t  mmd1_reg_async_sw_clk_en_pon_sdtx_smcbc:1;
	a_uint32_t  mmd1_reg_uphy_pon_tx_sw_rstn:1;
	a_uint32_t  mmd1_reg_uphy_pon_rx_sw_rstn:1;
	a_uint32_t  mmd1_reg_async_sw_clk_en_pon_sdrx_smcbc:1;
	a_uint32_t  _reserved0:25;
};

union pon_smcbc_ctrl_u {
	a_uint32_t val;
	struct pon_smcbc_ctrl bf;
};

/*[register] FUNC_RST_PON - 0x5B8*/
#define FUNC_RST_PON
#define FUNC_RST_PON_ADDRESS 0x5B8
#define FUNC_RST_PON_NUM     3
#define FUNC_RST_PON_INC     0x1
#define FUNC_RST_PON_TYPE    REG_TYPE_RW
#define FUNC_RST_PON_DEFAULT 0x33
	/*[field] MMD1_REG_FUNC_MBIST_SEL*/
	#define FUNC_RST_PON_MMD1_REG_FUNC_MBIST_SEL
	#define FUNC_RST_PON_MMD1_REG_FUNC_MBIST_SEL_OFFSET  6
	#define FUNC_RST_PON_MMD1_REG_FUNC_MBIST_SEL_LEN     2
	#define FUNC_RST_PON_MMD1_REG_FUNC_MBIST_SEL_DEFAULT 0x0
	/*[field] MMD1_REG_XPCS_ENABLE*/
	#define FUNC_RST_PON_MMD1_REG_XPCS_ENABLE
	#define FUNC_RST_PON_MMD1_REG_XPCS_ENABLE_OFFSET  5
	#define FUNC_RST_PON_MMD1_REG_XPCS_ENABLE_LEN     1
	#define FUNC_RST_PON_MMD1_REG_XPCS_ENABLE_DEFAULT 0x1
	/*[field] MMD1_REG_QSGMII_ENABLE*/
	#define FUNC_RST_PON_MMD1_REG_QSGMII_ENABLE
	#define FUNC_RST_PON_MMD1_REG_QSGMII_ENABLE_OFFSET  4
	#define FUNC_RST_PON_MMD1_REG_QSGMII_ENABLE_LEN     1
	#define FUNC_RST_PON_MMD1_REG_QSGMII_ENABLE_DEFAULT 0x1
	/*[field] MMD1_REG_FUNC_RST_PON_RX_N*/
	#define FUNC_RST_PON_MMD1_REG_FUNC_RST_PON_RX_N
	#define FUNC_RST_PON_MMD1_REG_FUNC_RST_PON_RX_N_OFFSET  1
	#define FUNC_RST_PON_MMD1_REG_FUNC_RST_PON_RX_N_LEN     1
	#define FUNC_RST_PON_MMD1_REG_FUNC_RST_PON_RX_N_DEFAULT 0x1
	/*[field] MMD1_REG_FUNC_RST_PON_TX_N*/
	#define FUNC_RST_PON_MMD1_REG_FUNC_RST_PON_TX_N
	#define FUNC_RST_PON_MMD1_REG_FUNC_RST_PON_TX_N_OFFSET  0
	#define FUNC_RST_PON_MMD1_REG_FUNC_RST_PON_TX_N_LEN     1
	#define FUNC_RST_PON_MMD1_REG_FUNC_RST_PON_TX_N_DEFAULT 0x1

struct func_rst_pon {
	a_uint32_t  mmd1_reg_func_rst_pon_tx_n:1;
	a_uint32_t  mmd1_reg_func_rst_pon_rx_n:1;
	a_uint32_t  _reserved0:2;
	a_uint32_t  mmd1_reg_qsgmii_enable:1;
	a_uint32_t  mmd1_reg_xpcs_enable:1;
	a_uint32_t  mmd1_reg_func_mbist_sel:2;
	a_uint32_t  _reserved1:24;
};

union func_rst_pon_u {
	a_uint32_t val;
	struct func_rst_pon bf;
};

/*[register] PON_REG_SOURCE_SEL1 - 0x5FC*/
#define PON_REG_SOURCE_SEL1
#define PON_REG_SOURCE_SEL1_ADDRESS 0x5FC
#define PON_REG_SOURCE_SEL1_NUM     3
#define PON_REG_SOURCE_SEL1_INC     0x1
#define PON_REG_SOURCE_SEL1_TYPE    REG_TYPE_RW
#define PON_REG_SOURCE_SEL1_DEFAULT 0x0
	/*[field] MMD1_REG_SRC_PON_MODE_EXT_INTERNAL*/
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_MODE_EXT_INTERNAL
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_MODE_EXT_INTERNAL_OFFSET  10
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_MODE_EXT_INTERNAL_LEN     1
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_MODE_EXT_INTERNAL_DEFAULT 0x0
	/*[field] MMD1_REG_SRC_PON_PLL_CP_SEL*/
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_CP_SEL
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_CP_SEL_OFFSET  8
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_CP_SEL_LEN     2
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_CP_SEL_DEFAULT 0x0
	/*[field] MMD1_REG_SRC_PON_PLL_LPF_C2*/
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_LPF_C2
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_LPF_C2_OFFSET  6
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_LPF_C2_LEN     2
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_LPF_C2_DEFAULT 0x0
	/*[field] MMD1_REG_SRC_PON_PLL_LPF_RES*/
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_LPF_RES
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_LPF_RES_OFFSET  4
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_LPF_RES_LEN     2
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_LPF_RES_DEFAULT 0x0
	/*[field] MMD1_REG_SRC_PON_PLL_VCO_AMP*/
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_VCO_AMP
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_VCO_AMP_OFFSET  2
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_VCO_AMP_LEN     2
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_VCO_AMP_DEFAULT 0x0
	/*[field] MMD1_REG_SRC_PON_PLL_VCO_TEMP_CMP*/
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_VCO_TEMP_CMP
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_VCO_TEMP_CMP_OFFSET  0
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_VCO_TEMP_CMP_LEN     2
	#define PON_REG_SOURCE_SEL1_MMD1_REG_SRC_PON_PLL_VCO_TEMP_CMP_DEFAULT 0x0

struct pon_reg_source_sel1 {
	a_uint32_t  mmd1_reg_src_pon_pll_vco_temp_cmp:2;
	a_uint32_t  mmd1_reg_src_pon_pll_vco_amp:2;
	a_uint32_t  mmd1_reg_src_pon_pll_lpf_res:2;
	a_uint32_t  mmd1_reg_src_pon_pll_lpf_c2:2;
	a_uint32_t  mmd1_reg_src_pon_pll_cp_sel:2;
	a_uint32_t  mmd1_reg_src_pon_mode_ext_internal:1;
	a_uint32_t  _reserved0:21;
};

union pon_reg_source_sel1_u {
	a_uint32_t val;
	struct pon_reg_source_sel1 bf;
};

/*[register] PON_CDR_LOCK_WAIT_CNT - 0x610*/
#define PON_CDR_LOCK_WAIT_CNT
#define PON_CDR_LOCK_WAIT_CNT_ADDRESS 0x610
#define PON_CDR_LOCK_WAIT_CNT_NUM     3
#define PON_CDR_LOCK_WAIT_CNT_INC     0x1
#define PON_CDR_LOCK_WAIT_CNT_TYPE    REG_TYPE_RW
#define PON_CDR_LOCK_WAIT_CNT_DEFAULT 0x6752
	/*[field] MMD1_REG_REG_PON_CDR_LOCK_WAIT_CNT*/
	#define PON_CDR_LOCK_WAIT_CNT_MMD1_REG_REG_PON_CDR_LOCK_WAIT_CNT
	#define PON_CDR_LOCK_WAIT_CNT_MMD1_REG_REG_PON_CDR_LOCK_WAIT_CNT_OFFSET  0
	#define PON_CDR_LOCK_WAIT_CNT_MMD1_REG_REG_PON_CDR_LOCK_WAIT_CNT_LEN     16
	#define PON_CDR_LOCK_WAIT_CNT_MMD1_REG_REG_PON_CDR_LOCK_WAIT_CNT_DEFAULT 0x6752

struct pon_cdr_lock_wait_cnt {
	a_uint32_t  mmd1_reg_reg_pon_cdr_lock_wait_cnt:16;
	a_uint32_t  _reserved0:16;
};

union pon_cdr_lock_wait_cnt_u {
	a_uint32_t val;
	struct pon_cdr_lock_wait_cnt bf;
};

/*[register] JCCDR_DIG_CTRL1 - 0x644*/
#define JCCDR_DIG_CTRL1
#define JCCDR_DIG_CTRL1_ADDRESS 0x644
#define JCCDR_DIG_CTRL1_NUM     3
#define JCCDR_DIG_CTRL1_INC     0x1
#define JCCDR_DIG_CTRL1_TYPE    REG_TYPE_RW
#define JCCDR_DIG_CTRL1_DEFAULT 0xB4
	/*[field] MMD1_REG_PON_VCO_DONE_WAIT_SMPL*/
	#define JCCDR_DIG_CTRL1_MMD1_REG_PON_VCO_DONE_WAIT_SMPL
	#define JCCDR_DIG_CTRL1_MMD1_REG_PON_VCO_DONE_WAIT_SMPL_OFFSET  11
	#define JCCDR_DIG_CTRL1_MMD1_REG_PON_VCO_DONE_WAIT_SMPL_LEN     1
	#define JCCDR_DIG_CTRL1_MMD1_REG_PON_VCO_DONE_WAIT_SMPL_DEFAULT 0x0
	/*[field] MMD1_REG_JCCDR_REGULAR_LOCK*/
	#define JCCDR_DIG_CTRL1_MMD1_REG_JCCDR_REGULAR_LOCK
	#define JCCDR_DIG_CTRL1_MMD1_REG_JCCDR_REGULAR_LOCK_OFFSET  10
	#define JCCDR_DIG_CTRL1_MMD1_REG_JCCDR_REGULAR_LOCK_LEN     1
	#define JCCDR_DIG_CTRL1_MMD1_REG_JCCDR_REGULAR_LOCK_DEFAULT 0x0
	/*[field] MMD1_REG_CDR_1ST_WAIT_PON_VCO*/
	#define JCCDR_DIG_CTRL1_MMD1_REG_CDR_1ST_WAIT_PON_VCO
	#define JCCDR_DIG_CTRL1_MMD1_REG_CDR_1ST_WAIT_PON_VCO_OFFSET  9
	#define JCCDR_DIG_CTRL1_MMD1_REG_CDR_1ST_WAIT_PON_VCO_LEN     1
	#define JCCDR_DIG_CTRL1_MMD1_REG_CDR_1ST_WAIT_PON_VCO_DEFAULT 0x0
	/*[field] MMD1_REG_JCCDR_BYPASS*/
	#define JCCDR_DIG_CTRL1_MMD1_REG_JCCDR_BYPASS
	#define JCCDR_DIG_CTRL1_MMD1_REG_JCCDR_BYPASS_OFFSET  8
	#define JCCDR_DIG_CTRL1_MMD1_REG_JCCDR_BYPASS_LEN     1
	#define JCCDR_DIG_CTRL1_MMD1_REG_JCCDR_BYPASS_DEFAULT 0x0
	/*[field] MMD1_REG_PON_PLL_BYPASS*/
	#define JCCDR_DIG_CTRL1_MMD1_REG_PON_PLL_BYPASS
	#define JCCDR_DIG_CTRL1_MMD1_REG_PON_PLL_BYPASS_OFFSET  7
	#define JCCDR_DIG_CTRL1_MMD1_REG_PON_PLL_BYPASS_LEN     1
	#define JCCDR_DIG_CTRL1_MMD1_REG_PON_PLL_BYPASS_DEFAULT 0x1
	/*[field] MMD1_REG_JCCDR_RXCLK_FLOOP_SEL*/
	#define JCCDR_DIG_CTRL1_MMD1_REG_JCCDR_RXCLK_FLOOP_SEL
	#define JCCDR_DIG_CTRL1_MMD1_REG_JCCDR_RXCLK_FLOOP_SEL_OFFSET  6
	#define JCCDR_DIG_CTRL1_MMD1_REG_JCCDR_RXCLK_FLOOP_SEL_LEN     1
	#define JCCDR_DIG_CTRL1_MMD1_REG_JCCDR_RXCLK_FLOOP_SEL_DEFAULT 0x0
	/*[field] MMD1_REG_JCCDR_RXCLK_FLOOP_SW_RSTN*/
	#define JCCDR_DIG_CTRL1_MMD1_REG_JCCDR_RXCLK_FLOOP_SW_RSTN
	#define JCCDR_DIG_CTRL1_MMD1_REG_JCCDR_RXCLK_FLOOP_SW_RSTN_OFFSET  5
	#define JCCDR_DIG_CTRL1_MMD1_REG_JCCDR_RXCLK_FLOOP_SW_RSTN_LEN     1
	#define JCCDR_DIG_CTRL1_MMD1_REG_JCCDR_RXCLK_FLOOP_SW_RSTN_DEFAULT 0x1
	/*[field] MMD1_REG_SA_CALIB_BYPS_2ND*/
	#define JCCDR_DIG_CTRL1_MMD1_REG_SA_CALIB_BYPS_2ND
	#define JCCDR_DIG_CTRL1_MMD1_REG_SA_CALIB_BYPS_2ND_OFFSET  4
	#define JCCDR_DIG_CTRL1_MMD1_REG_SA_CALIB_BYPS_2ND_LEN     1
	#define JCCDR_DIG_CTRL1_MMD1_REG_SA_CALIB_BYPS_2ND_DEFAULT 0x1
	/*[field] MMD1_REG_PON_CALIB_CLK_DIV*/
	#define JCCDR_DIG_CTRL1_MMD1_REG_PON_CALIB_CLK_DIV
	#define JCCDR_DIG_CTRL1_MMD1_REG_PON_CALIB_CLK_DIV_OFFSET  2
	#define JCCDR_DIG_CTRL1_MMD1_REG_PON_CALIB_CLK_DIV_LEN     2
	#define JCCDR_DIG_CTRL1_MMD1_REG_PON_CALIB_CLK_DIV_DEFAULT 0x1
	/*[field] MMD1_REG_PON_VCO_CALIB_CLK_DIV*/
	#define JCCDR_DIG_CTRL1_MMD1_REG_PON_VCO_CALIB_CLK_DIV
	#define JCCDR_DIG_CTRL1_MMD1_REG_PON_VCO_CALIB_CLK_DIV_OFFSET  0
	#define JCCDR_DIG_CTRL1_MMD1_REG_PON_VCO_CALIB_CLK_DIV_LEN     2
	#define JCCDR_DIG_CTRL1_MMD1_REG_PON_VCO_CALIB_CLK_DIV_DEFAULT 0x0

struct jccdr_dig_ctrl1 {
	a_uint32_t  mmd1_reg_pon_vco_calib_clk_div:2;
	a_uint32_t  mmd1_reg_pon_calib_clk_div:2;
	a_uint32_t  mmd1_reg_sa_calib_byps_2nd:1;
	a_uint32_t  mmd1_reg_jccdr_rxclk_floop_sw_rstn:1;
	a_uint32_t  mmd1_reg_jccdr_rxclk_floop_sel:1;
	a_uint32_t  mmd1_reg_pon_pll_bypass:1;
	a_uint32_t  mmd1_reg_jccdr_bypass:1;
	a_uint32_t  mmd1_reg_cdr_1st_wait_pon_vco:1;
	a_uint32_t  mmd1_reg_jccdr_regular_lock:1;
	a_uint32_t  mmd1_reg_pon_vco_done_wait_smpl:1;
	a_uint32_t  _reserved0:20;
};

union jccdr_dig_ctrl1_u {
	a_uint32_t val;
	struct jccdr_dig_ctrl1 bf;
};

/*[register] JCCDR_CALIB_STS_DEBUG - 0x688*/
#define JCCDR_CALIB_STS_DEBUG
#define JCCDR_CALIB_STS_DEBUG_ADDRESS 0x688
#define JCCDR_CALIB_STS_DEBUG_NUM     3
#define JCCDR_CALIB_STS_DEBUG_INC     0x1
#define JCCDR_CALIB_STS_DEBUG_TYPE    REG_TYPE_RO
#define JCCDR_CALIB_STS_DEBUG_DEFAULT 0x0

	/*[field] MMD1_REG_JCCDR_STG_STATE*/
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_JCCDR_STG_STATE
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_JCCDR_STG_STATE_OFFSET  9
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_JCCDR_STG_STATE_LEN     2
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_JCCDR_STG_STATE_DEFAULT 0x0

	/*[field] MMD1_REG_SA_CALIB_DONE_ALL*/
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_SA_CALIB_DONE_ALL
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_SA_CALIB_DONE_ALL_OFFSET  8
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_SA_CALIB_DONE_ALL_LEN     1
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_SA_CALIB_DONE_ALL_DEFAULT 0x0

	/*[field] MMD1_REG_SDRX_LOCK*/
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_SDRX_LOCK
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_SDRX_LOCK_OFFSET  7
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_SDRX_LOCK_LEN     1
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_SDRX_LOCK_DEFAULT 0x0

	/*[field] MMD1_REG_CDR_1ST_LOCKED*/
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_CDR_1ST_LOCKED
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_CDR_1ST_LOCKED_OFFSET  6
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_CDR_1ST_LOCKED_LEN     1
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_CDR_1ST_LOCKED_DEFAULT 0x0

	/*[field] MMD1_REG_CDR_1ST_ENABLE*/
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_CDR_1ST_ENABLE
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_CDR_1ST_ENABLE_OFFSET  5
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_CDR_1ST_ENABLE_LEN     1
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_CDR_1ST_ENABLE_DEFAULT 0x0

	/*[field] MMD1_REG_SMPL_CAL_READY_2ND*/
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_SMPL_CAL_READY_2ND
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_SMPL_CAL_READY_2ND_OFFSET  4
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_SMPL_CAL_READY_2ND_LEN     1
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_SMPL_CAL_READY_2ND_DEFAULT 0x0

	/*[field] MMD1_REG_JCCDR_RX_CAL_OUT*/
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_JCCDR_RX_CAL_OUT
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_JCCDR_RX_CAL_OUT_OFFSET  3
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_JCCDR_RX_CAL_OUT_LEN     1
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_JCCDR_RX_CAL_OUT_DEFAULT 0x0

	/*[field] MMD1_REG_CALIBRATION_DONE_UPHYPLL*/
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_CALIBRATION_DONE_UPHYPLL
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_CALIBRATION_DONE_UPHYPLL_OFFSET  2
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_CALIBRATION_DONE_UPHYPLL_LEN     1
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_CALIBRATION_DONE_UPHYPLL_DEFAULT 0x0

	/*[field] MMD1_REG_CALIBRATION_DONE_JCPLL*/
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_CALIBRATION_DONE_JCPLL
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_CALIBRATION_DONE_JCPLL_OFFSET  1
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_CALIBRATION_DONE_JCPLL_LEN     1
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_CALIBRATION_DONE_JCPLL_DEFAULT 0x0

	/*[field] MMD1_REG_JC_PLL_LOCKED*/
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_JC_PLL_LOCKED
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_JC_PLL_LOCKED_OFFSET  0
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_JC_PLL_LOCKED_LEN     1
	#define JCCDR_CALIB_STS_DEBUG_MMD1_REG_JC_PLL_LOCKED_DEFAULT 0x0

struct jccdr_calib_sts_debug {
	a_uint32_t  mmd1_reg_jc_pll_locked:1;
	a_uint32_t  mmd1_reg_calibration_done_jcpll:1;
	a_uint32_t  mmd1_reg_calibration_done_uphypll:1;
	a_uint32_t  mmd1_reg_jccdr_rx_cal_out:1;
	a_uint32_t  mmd1_reg_smpl_cal_ready_2nd:1;
	a_uint32_t  mmd1_reg_cdr_1st_enable:1;
	a_uint32_t  mmd1_reg_cdr_1st_locked:1;
	a_uint32_t  mmd1_reg_sdrx_lock:1;
	a_uint32_t  mmd1_reg_sa_calib_done_all:1;
	a_uint32_t  mmd1_reg_jccdr_stg_state:2;
	a_uint32_t  _reserved0:21;
};

union jccdr_calib_sts_debug_u {
	a_uint32_t val;
	struct jccdr_calib_sts_debug bf;
};

/*[register] PON_CDR_LOCK_WAIT_CNT_EXTEND - 0x6A8*/
#define PON_CDR_LOCK_WAIT_CNT_EXTEND
#define PON_CDR_LOCK_WAIT_CNT_EXTEND_ADDRESS 0x6A8
#define PON_CDR_LOCK_WAIT_CNT_EXTEND_NUM     3
#define PON_CDR_LOCK_WAIT_CNT_EXTEND_INC     0x1
#define PON_CDR_LOCK_WAIT_CNT_EXTEND_TYPE    REG_TYPE_RW
#define PON_CDR_LOCK_WAIT_CNT_EXTEND_DEFAULT 0x0
	/*[field] MMD1_REG_REG_PON_CDR_LOCK_WAIT_CNT_EXTEND*/
	#define PON_CDR_LOCK_WAIT_CNT_EXTEND_MMD1_REG_REG_PON_CDR_LOCK_WAIT_CNT_EXTEND
	#define PON_CDR_LOCK_WAIT_CNT_EXTEND_MMD1_REG_REG_PON_CDR_LOCK_WAIT_CNT_EXTEND_OFFSET  0
	#define PON_CDR_LOCK_WAIT_CNT_EXTEND_MMD1_REG_REG_PON_CDR_LOCK_WAIT_CNT_EXTEND_LEN     16
	#define PON_CDR_LOCK_WAIT_CNT_EXTEND_MMD1_REG_REG_PON_CDR_LOCK_WAIT_CNT_EXTEND_DEFAULT 0x0

struct pon_cdr_lock_wait_cnt_extend {
	a_uint32_t  mmd1_reg_reg_pon_cdr_lock_wait_cnt_extend:16;
	a_uint32_t  _reserved0:16;
};

union pon_cdr_lock_wait_cnt_extend_u {
	a_uint32_t val;
	struct pon_cdr_lock_wait_cnt_extend bf;
};

/*[register] JCCDR_STG1_LOW - 0x6B0*/
#define JCCDR_STG1_LOW
#define JCCDR_STG1_LOW_ADDRESS 0x6B0
#define JCCDR_STG1_LOW_NUM     3
#define JCCDR_STG1_LOW_INC     0x1
#define JCCDR_STG1_LOW_TYPE    REG_TYPE_RW
#define JCCDR_STG1_LOW_DEFAULT 0x964
	/*[field] MMD1_REG_REG_JCCDR_STG1_15_0*/
	#define JCCDR_STG1_LOW_MMD1_REG_REG_JCCDR_STG1_15_0
	#define JCCDR_STG1_LOW_MMD1_REG_REG_JCCDR_STG1_15_0_OFFSET  0
	#define JCCDR_STG1_LOW_MMD1_REG_REG_JCCDR_STG1_15_0_LEN     16
	#define JCCDR_STG1_LOW_MMD1_REG_REG_JCCDR_STG1_15_0_DEFAULT 0x964

struct jccdr_stg1_low {
	a_uint32_t  mmd1_reg_reg_jccdr_stg1_15_0:16;
	a_uint32_t  _reserved0:16;
};

union jccdr_stg1_low_u {
	a_uint32_t val;
	struct jccdr_stg1_low bf;
};

/*[register] JCCDR_STG2_LOW - 0x6B8*/
#define JCCDR_STG2_LOW
#define JCCDR_STG2_LOW_ADDRESS 0x6B8
#define JCCDR_STG2_LOW_NUM     3
#define JCCDR_STG2_LOW_INC     0x1
#define JCCDR_STG2_LOW_TYPE    REG_TYPE_RW
#define JCCDR_STG2_LOW_DEFAULT 0x12CA
	/*[field] MMD1_REG_REG_JCCDR_STG2_15_0*/
	#define JCCDR_STG2_LOW_MMD1_REG_REG_JCCDR_STG2_15_0
	#define JCCDR_STG2_LOW_MMD1_REG_REG_JCCDR_STG2_15_0_OFFSET  0
	#define JCCDR_STG2_LOW_MMD1_REG_REG_JCCDR_STG2_15_0_LEN     16
	#define JCCDR_STG2_LOW_MMD1_REG_REG_JCCDR_STG2_15_0_DEFAULT 0x12CA

struct jccdr_stg2_low {
	a_uint32_t  mmd1_reg_reg_jccdr_stg2_15_0:16;
	a_uint32_t  _reserved0:16;
};

union jccdr_stg2_low_u {
	a_uint32_t val;
	struct jccdr_stg2_low bf;
};

/*[register] JCCDR_STG3_LOW - 0x6C0*/
#define JCCDR_STG3_LOW
#define JCCDR_STG3_LOW_ADDRESS 0x6C0
#define JCCDR_STG3_LOW_NUM     3
#define JCCDR_STG3_LOW_INC     0x1
#define JCCDR_STG3_LOW_TYPE    REG_TYPE_RW
#define JCCDR_STG3_LOW_DEFAULT 0x385A
	/*[field] MMD1_REG_REG_JCCDR_STG3_15_0*/
	#define JCCDR_STG3_LOW_MMD1_REG_REG_JCCDR_STG3_15_0
	#define JCCDR_STG3_LOW_MMD1_REG_REG_JCCDR_STG3_15_0_OFFSET  0
	#define JCCDR_STG3_LOW_MMD1_REG_REG_JCCDR_STG3_15_0_LEN     16
	#define JCCDR_STG3_LOW_MMD1_REG_REG_JCCDR_STG3_15_0_DEFAULT 0x385A

struct jccdr_stg3_low {
	a_uint32_t  mmd1_reg_reg_jccdr_stg3_15_0:16;
	a_uint32_t  _reserved0:16;
};

union jccdr_stg3_low_u {
	a_uint32_t val;
	struct jccdr_stg3_low bf;
};

/*[register] JCCDR_TUNE_CNT1_LOW - 0x6DC*/
#define JCCDR_TUNE_CNT1_LOW
#define JCCDR_TUNE_CNT1_LOW_ADDRESS 0x6DC
#define JCCDR_TUNE_CNT1_LOW_NUM     3
#define JCCDR_TUNE_CNT1_LOW_INC     0x1
#define JCCDR_TUNE_CNT1_LOW_TYPE    REG_TYPE_RW
#define JCCDR_TUNE_CNT1_LOW_DEFAULT 0x10E0
	/*[field] MMD1_REG_REG_JCCDR_TUNE_CNT1_15_0*/
	#define JCCDR_TUNE_CNT1_LOW_MMD1_REG_REG_JCCDR_TUNE_CNT1_15_0
	#define JCCDR_TUNE_CNT1_LOW_MMD1_REG_REG_JCCDR_TUNE_CNT1_15_0_OFFSET  0
	#define JCCDR_TUNE_CNT1_LOW_MMD1_REG_REG_JCCDR_TUNE_CNT1_15_0_LEN     16
	#define JCCDR_TUNE_CNT1_LOW_MMD1_REG_REG_JCCDR_TUNE_CNT1_15_0_DEFAULT 0x10E0

struct jccdr_tune_cnt1_low {
	a_uint32_t  mmd1_reg_reg_jccdr_tune_cnt1_15_0:16;
	a_uint32_t  _reserved0:16;
};

union jccdr_tune_cnt1_low_u {
	a_uint32_t val;
	struct jccdr_tune_cnt1_low bf;
};

/*[register] JCCDR_TUNE_CNT2_LOW - 0x6E4*/
#define JCCDR_TUNE_CNT2_LOW
#define JCCDR_TUNE_CNT2_LOW_ADDRESS 0x6E4
#define JCCDR_TUNE_CNT2_LOW_NUM     3
#define JCCDR_TUNE_CNT2_LOW_INC     0x1
#define JCCDR_TUNE_CNT2_LOW_TYPE    REG_TYPE_RW
#define JCCDR_TUNE_CNT2_LOW_DEFAULT 0x3660
	/*[field] MMD1_REG_REG_JCCDR_TUNE_CNT2_15_0*/
	#define JCCDR_TUNE_CNT2_LOW_MMD1_REG_REG_JCCDR_TUNE_CNT2_15_0
	#define JCCDR_TUNE_CNT2_LOW_MMD1_REG_REG_JCCDR_TUNE_CNT2_15_0_OFFSET  0
	#define JCCDR_TUNE_CNT2_LOW_MMD1_REG_REG_JCCDR_TUNE_CNT2_15_0_LEN     16
	#define JCCDR_TUNE_CNT2_LOW_MMD1_REG_REG_JCCDR_TUNE_CNT2_15_0_DEFAULT 0x3660

struct jccdr_tune_cnt2_low {
	a_uint32_t  mmd1_reg_reg_jccdr_tune_cnt2_15_0:16;
	a_uint32_t  _reserved0:16;
};

union jccdr_tune_cnt2_low_u {
	a_uint32_t val;
	struct jccdr_tune_cnt2_low bf;
};

/*[register] JCCDR_FLOOP_GAIN_TUNE_VAL - 0x6EC*/
#define JCCDR_FLOOP_GAIN_TUNE_VAL
#define JCCDR_FLOOP_GAIN_TUNE_VAL_ADDRESS 0x6EC
#define JCCDR_FLOOP_GAIN_TUNE_VAL_NUM     3
#define JCCDR_FLOOP_GAIN_TUNE_VAL_INC     0x1
#define JCCDR_FLOOP_GAIN_TUNE_VAL_TYPE    REG_TYPE_RW
#define JCCDR_FLOOP_GAIN_TUNE_VAL_DEFAULT 0x5983
	/*[field] MMD1_REG_REG_JCCDR_FLOOP_GAIN_TUNE2*/
	#define JCCDR_FLOOP_GAIN_TUNE_VAL_MMD1_REG_REG_JCCDR_FLOOP_GAIN_TUNE2
	#define JCCDR_FLOOP_GAIN_TUNE_VAL_MMD1_REG_REG_JCCDR_FLOOP_GAIN_TUNE2_OFFSET  11
	#define JCCDR_FLOOP_GAIN_TUNE_VAL_MMD1_REG_REG_JCCDR_FLOOP_GAIN_TUNE2_LEN     5
	#define JCCDR_FLOOP_GAIN_TUNE_VAL_MMD1_REG_REG_JCCDR_FLOOP_GAIN_TUNE2_DEFAULT 0xB
	/*[field] MMD1_REG_REG_JCCDR_FLOOP_GAIN_TUNE1*/
	#define JCCDR_FLOOP_GAIN_TUNE_VAL_MMD1_REG_REG_JCCDR_FLOOP_GAIN_TUNE1
	#define JCCDR_FLOOP_GAIN_TUNE_VAL_MMD1_REG_REG_JCCDR_FLOOP_GAIN_TUNE1_OFFSET  6
	#define JCCDR_FLOOP_GAIN_TUNE_VAL_MMD1_REG_REG_JCCDR_FLOOP_GAIN_TUNE1_LEN     5
	#define JCCDR_FLOOP_GAIN_TUNE_VAL_MMD1_REG_REG_JCCDR_FLOOP_GAIN_TUNE1_DEFAULT 0x6
	/*[field] MMD1_REG_REG_JCCDR_FLOOP_GAIN_TUNE0*/
	#define JCCDR_FLOOP_GAIN_TUNE_VAL_MMD1_REG_REG_JCCDR_FLOOP_GAIN_TUNE0
	#define JCCDR_FLOOP_GAIN_TUNE_VAL_MMD1_REG_REG_JCCDR_FLOOP_GAIN_TUNE0_OFFSET  1
	#define JCCDR_FLOOP_GAIN_TUNE_VAL_MMD1_REG_REG_JCCDR_FLOOP_GAIN_TUNE0_LEN     5
	#define JCCDR_FLOOP_GAIN_TUNE_VAL_MMD1_REG_REG_JCCDR_FLOOP_GAIN_TUNE0_DEFAULT 0x1
	/*[field] MMD1_REG_JCCDR_FLOOP_GAIN_TUNE_EN*/
	#define JCCDR_FLOOP_GAIN_TUNE_VAL_MMD1_REG_JCCDR_FLOOP_GAIN_TUNE_EN
	#define JCCDR_FLOOP_GAIN_TUNE_VAL_MMD1_REG_JCCDR_FLOOP_GAIN_TUNE_EN_OFFSET  0
	#define JCCDR_FLOOP_GAIN_TUNE_VAL_MMD1_REG_JCCDR_FLOOP_GAIN_TUNE_EN_LEN     1
	#define JCCDR_FLOOP_GAIN_TUNE_VAL_MMD1_REG_JCCDR_FLOOP_GAIN_TUNE_EN_DEFAULT 0x1

struct jccdr_floop_gain_tune_val {
	a_uint32_t  mmd1_reg_jccdr_floop_gain_tune_en:1;
	a_uint32_t  mmd1_reg_reg_jccdr_floop_gain_tune0:5;
	a_uint32_t  mmd1_reg_reg_jccdr_floop_gain_tune1:5;
	a_uint32_t  mmd1_reg_reg_jccdr_floop_gain_tune2:5;
	a_uint32_t  _reserved0:16;
};

union jccdr_floop_gain_tune_val_u {
	a_uint32_t val;
	struct jccdr_floop_gain_tune_val bf;
};

/*[register] JCCDR_RGL_DIV_STG1_2 - 0x6F0*/
#define JCCDR_RGL_DIV_STG1_2
#define JCCDR_RGL_DIV_STG1_2_ADDRESS 0x6F0
#define JCCDR_RGL_DIV_STG1_2_NUM     3
#define JCCDR_RGL_DIV_STG1_2_INC     0x1
#define JCCDR_RGL_DIV_STG1_2_TYPE    REG_TYPE_RW
#define JCCDR_RGL_DIV_STG1_2_DEFAULT 0x0
	/*[field] MMD1_REG_REG_RGL_CDR_DIV_STG2*/
	#define JCCDR_RGL_DIV_STG1_2_MMD1_REG_REG_RGL_CDR_DIV_STG2
	#define JCCDR_RGL_DIV_STG1_2_MMD1_REG_REG_RGL_CDR_DIV_STG2_OFFSET  8
	#define JCCDR_RGL_DIV_STG1_2_MMD1_REG_REG_RGL_CDR_DIV_STG2_LEN     8
	#define JCCDR_RGL_DIV_STG1_2_MMD1_REG_REG_RGL_CDR_DIV_STG2_DEFAULT 0x0
	/*[field] MMD1_REG_REG_RGL_CDR_DIV_STG1*/
	#define JCCDR_RGL_DIV_STG1_2_MMD1_REG_REG_RGL_CDR_DIV_STG1
	#define JCCDR_RGL_DIV_STG1_2_MMD1_REG_REG_RGL_CDR_DIV_STG1_OFFSET  0
	#define JCCDR_RGL_DIV_STG1_2_MMD1_REG_REG_RGL_CDR_DIV_STG1_LEN     8
	#define JCCDR_RGL_DIV_STG1_2_MMD1_REG_REG_RGL_CDR_DIV_STG1_DEFAULT 0x0

struct jccdr_rgl_div_stg1_2 {
	a_uint32_t  mmd1_reg_reg_rgl_cdr_div_stg1:8;
	a_uint32_t  mmd1_reg_reg_rgl_cdr_div_stg2:8;
	a_uint32_t  _reserved0:16;
};

union jccdr_rgl_div_stg1_2_u {
	a_uint32_t val;
	struct jccdr_rgl_div_stg1_2 bf;
};

/*[register] JCCDR_FST_DIV_STG1_2_STEP1 - 0x6F4*/
#define JCCDR_FST_DIV_STG1_2_STEP1
#define JCCDR_FST_DIV_STG1_2_STEP1_ADDRESS 0x6F4
#define JCCDR_FST_DIV_STG1_2_STEP1_NUM     3
#define JCCDR_FST_DIV_STG1_2_STEP1_INC     0x1
#define JCCDR_FST_DIV_STG1_2_STEP1_TYPE    REG_TYPE_RW
#define JCCDR_FST_DIV_STG1_2_STEP1_DEFAULT 0x404
	/*[field] MMD1_REG_REG_FST_CDR_DIV_STG2_STEP1*/
	#define JCCDR_FST_DIV_STG1_2_STEP1_MMD1_REG_REG_FST_CDR_DIV_STG2_STEP1
	#define JCCDR_FST_DIV_STG1_2_STEP1_MMD1_REG_REG_FST_CDR_DIV_STG2_STEP1_OFFSET  8
	#define JCCDR_FST_DIV_STG1_2_STEP1_MMD1_REG_REG_FST_CDR_DIV_STG2_STEP1_LEN     8
	#define JCCDR_FST_DIV_STG1_2_STEP1_MMD1_REG_REG_FST_CDR_DIV_STG2_STEP1_DEFAULT 0x4
	/*[field] MMD1_REG_REG_FST_CDR_DIV_STG1_STEP1*/
	#define JCCDR_FST_DIV_STG1_2_STEP1_MMD1_REG_REG_FST_CDR_DIV_STG1_STEP1
	#define JCCDR_FST_DIV_STG1_2_STEP1_MMD1_REG_REG_FST_CDR_DIV_STG1_STEP1_OFFSET  0
	#define JCCDR_FST_DIV_STG1_2_STEP1_MMD1_REG_REG_FST_CDR_DIV_STG1_STEP1_LEN     8
	#define JCCDR_FST_DIV_STG1_2_STEP1_MMD1_REG_REG_FST_CDR_DIV_STG1_STEP1_DEFAULT 0x4

struct jccdr_fst_div_stg1_2_step1 {
	a_uint32_t  mmd1_reg_reg_fst_cdr_div_stg1_step1:8;
	a_uint32_t  mmd1_reg_reg_fst_cdr_div_stg2_step1:8;
	a_uint32_t  _reserved0:16;
};

union jccdr_fst_div_stg1_2_step1_u {
	a_uint32_t val;
	struct jccdr_fst_div_stg1_2_step1 bf;
};

/*[register] JCCDR_FST_DIV_STG1_2_STEP2 - 0x6F8*/
#define JCCDR_FST_DIV_STG1_2_STEP2
#define JCCDR_FST_DIV_STG1_2_STEP2_ADDRESS 0x6F8
#define JCCDR_FST_DIV_STG1_2_STEP2_NUM     3
#define JCCDR_FST_DIV_STG1_2_STEP2_INC     0x1
#define JCCDR_FST_DIV_STG1_2_STEP2_TYPE    REG_TYPE_RW
#define JCCDR_FST_DIV_STG1_2_STEP2_DEFAULT 0x480
	/*[field] MMD1_REG_REG_FST_CDR_DIV_STG2_STEP2*/
	#define JCCDR_FST_DIV_STG1_2_STEP2_MMD1_REG_REG_FST_CDR_DIV_STG2_STEP2
	#define JCCDR_FST_DIV_STG1_2_STEP2_MMD1_REG_REG_FST_CDR_DIV_STG2_STEP2_OFFSET  8
	#define JCCDR_FST_DIV_STG1_2_STEP2_MMD1_REG_REG_FST_CDR_DIV_STG2_STEP2_LEN     8
	#define JCCDR_FST_DIV_STG1_2_STEP2_MMD1_REG_REG_FST_CDR_DIV_STG2_STEP2_DEFAULT 0x4
	/*[field] MMD1_REG_REG_FST_CDR_DIV_STG1_STEP2*/
	#define JCCDR_FST_DIV_STG1_2_STEP2_MMD1_REG_REG_FST_CDR_DIV_STG1_STEP2
	#define JCCDR_FST_DIV_STG1_2_STEP2_MMD1_REG_REG_FST_CDR_DIV_STG1_STEP2_OFFSET  0
	#define JCCDR_FST_DIV_STG1_2_STEP2_MMD1_REG_REG_FST_CDR_DIV_STG1_STEP2_LEN     8
	#define JCCDR_FST_DIV_STG1_2_STEP2_MMD1_REG_REG_FST_CDR_DIV_STG1_STEP2_DEFAULT 0x80

struct jccdr_fst_div_stg1_2_step2 {
	a_uint32_t  mmd1_reg_reg_fst_cdr_div_stg1_step2:8;
	a_uint32_t  mmd1_reg_reg_fst_cdr_div_stg2_step2:8;
	a_uint32_t  _reserved0:16;
};

union jccdr_fst_div_stg1_2_step2_u {
	a_uint32_t val;
	struct jccdr_fst_div_stg1_2_step2 bf;
};

/*[register] JCCDR_FST_DIV_STG1_2_STEP3 - 0x6FC*/
#define JCCDR_FST_DIV_STG1_2_STEP3
#define JCCDR_FST_DIV_STG1_2_STEP3_ADDRESS 0x6FC
#define JCCDR_FST_DIV_STG1_2_STEP3_NUM     3
#define JCCDR_FST_DIV_STG1_2_STEP3_INC     0x1
#define JCCDR_FST_DIV_STG1_2_STEP3_TYPE    REG_TYPE_RW
#define JCCDR_FST_DIV_STG1_2_STEP3_DEFAULT 0x8080
	/*[field] MMD1_REG_REG_FST_CDR_DIV_STG2_STEP3*/
	#define JCCDR_FST_DIV_STG1_2_STEP3_MMD1_REG_REG_FST_CDR_DIV_STG2_STEP3
	#define JCCDR_FST_DIV_STG1_2_STEP3_MMD1_REG_REG_FST_CDR_DIV_STG2_STEP3_OFFSET  8
	#define JCCDR_FST_DIV_STG1_2_STEP3_MMD1_REG_REG_FST_CDR_DIV_STG2_STEP3_LEN     8
	#define JCCDR_FST_DIV_STG1_2_STEP3_MMD1_REG_REG_FST_CDR_DIV_STG2_STEP3_DEFAULT 0x80
	/*[field] MMD1_REG_REG_FST_CDR_DIV_STG1_STEP3*/
	#define JCCDR_FST_DIV_STG1_2_STEP3_MMD1_REG_REG_FST_CDR_DIV_STG1_STEP3
	#define JCCDR_FST_DIV_STG1_2_STEP3_MMD1_REG_REG_FST_CDR_DIV_STG1_STEP3_OFFSET  0
	#define JCCDR_FST_DIV_STG1_2_STEP3_MMD1_REG_REG_FST_CDR_DIV_STG1_STEP3_LEN     8
	#define JCCDR_FST_DIV_STG1_2_STEP3_MMD1_REG_REG_FST_CDR_DIV_STG1_STEP3_DEFAULT 0x80

struct jccdr_fst_div_stg1_2_step3 {
	a_uint32_t  mmd1_reg_reg_fst_cdr_div_stg1_step3:8;
	a_uint32_t  mmd1_reg_reg_fst_cdr_div_stg2_step3:8;
	a_uint32_t  _reserved0:16;
};

union jccdr_fst_div_stg1_2_step3_u {
	a_uint32_t val;
	struct jccdr_fst_div_stg1_2_step3 bf;
};

/*[register] JCCDR_RGL_FST_DIV_STG3 - 0x700*/
#define JCCDR_RGL_FST_DIV_STG3
#define JCCDR_RGL_FST_DIV_STG3_ADDRESS 0x700
#define JCCDR_RGL_FST_DIV_STG3_NUM     3
#define JCCDR_RGL_FST_DIV_STG3_INC     0x1
#define JCCDR_RGL_FST_DIV_STG3_TYPE    REG_TYPE_RW
#define JCCDR_RGL_FST_DIV_STG3_DEFAULT 0x0
	/*[field] MMD1_REG_REG_FST_CDR_DIV_STG3_STEP3*/
	#define JCCDR_RGL_FST_DIV_STG3_MMD1_REG_REG_FST_CDR_DIV_STG3_STEP3
	#define JCCDR_RGL_FST_DIV_STG3_MMD1_REG_REG_FST_CDR_DIV_STG3_STEP3_OFFSET  12
	#define JCCDR_RGL_FST_DIV_STG3_MMD1_REG_REG_FST_CDR_DIV_STG3_STEP3_LEN     4
	#define JCCDR_RGL_FST_DIV_STG3_MMD1_REG_REG_FST_CDR_DIV_STG3_STEP3_DEFAULT 0x0
	/*[field] MMD1_REG_REG_FST_CDR_DIV_STG3_STEP2*/
	#define JCCDR_RGL_FST_DIV_STG3_MMD1_REG_REG_FST_CDR_DIV_STG3_STEP2
	#define JCCDR_RGL_FST_DIV_STG3_MMD1_REG_REG_FST_CDR_DIV_STG3_STEP2_OFFSET  8
	#define JCCDR_RGL_FST_DIV_STG3_MMD1_REG_REG_FST_CDR_DIV_STG3_STEP2_LEN     4
	#define JCCDR_RGL_FST_DIV_STG3_MMD1_REG_REG_FST_CDR_DIV_STG3_STEP2_DEFAULT 0x0
	/*[field] MMD1_REG_REG_FST_CDR_DIV_STG3_STEP1*/
	#define JCCDR_RGL_FST_DIV_STG3_MMD1_REG_REG_FST_CDR_DIV_STG3_STEP1
	#define JCCDR_RGL_FST_DIV_STG3_MMD1_REG_REG_FST_CDR_DIV_STG3_STEP1_OFFSET  4
	#define JCCDR_RGL_FST_DIV_STG3_MMD1_REG_REG_FST_CDR_DIV_STG3_STEP1_LEN     4
	#define JCCDR_RGL_FST_DIV_STG3_MMD1_REG_REG_FST_CDR_DIV_STG3_STEP1_DEFAULT 0x0
	/*[field] MMD1_REG_REG_RGL_CDR_DIV_STG3*/
	#define JCCDR_RGL_FST_DIV_STG3_MMD1_REG_REG_RGL_CDR_DIV_STG3
	#define JCCDR_RGL_FST_DIV_STG3_MMD1_REG_REG_RGL_CDR_DIV_STG3_OFFSET  0
	#define JCCDR_RGL_FST_DIV_STG3_MMD1_REG_REG_RGL_CDR_DIV_STG3_LEN     4
	#define JCCDR_RGL_FST_DIV_STG3_MMD1_REG_REG_RGL_CDR_DIV_STG3_DEFAULT 0x0

struct jccdr_rgl_fst_div_stg3 {
	a_uint32_t  mmd1_reg_reg_rgl_cdr_div_stg3:4;
	a_uint32_t  mmd1_reg_reg_fst_cdr_div_stg3_step1:4;
	a_uint32_t  mmd1_reg_reg_fst_cdr_div_stg3_step2:4;
	a_uint32_t  mmd1_reg_reg_fst_cdr_div_stg3_step3:4;
	a_uint32_t  _reserved0:16;
};

union jccdr_rgl_fst_div_stg3_u {
	a_uint32_t val;
	struct jccdr_rgl_fst_div_stg3 bf;
};

#endif /* _HMSPPE_UNIPHY_REG_H_ */
