/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: ISC
 */
#include "hsl_dev.h"
#include "hmsppe/hppe_acl_reg.h"
#include "hmsppe/hppe_bm_reg.h"
#include "hmsppe/hppe_ctrlpkt_reg.h"
#include "hmsppe/hppe_fdb_reg.h"
#include "hmsppe/hppe_flow_reg.h"
#include "hmsppe/hppe_ip_reg.h"
#include "hmsppe/hppe_mib_reg.h"
#include "hmsppe/hppe_mirror_reg.h"
#include "hmsppe/hppe_policer_reg.h"
#include "hmsppe/hppe_portctrl_reg.h"
#include "hmsppe/hppe_portvlan_reg.h"
#include "hmsppe/hppe_qm_reg.h"
#include "hmsppe/hppe_qos_reg.h"
#include "hmsppe/hppe_rss_reg.h"
#include "hmsppe/hppe_sec_reg.h"
#include "hmsppe/hppe_servcode_reg.h"
#include "hmsppe/hppe_shaper_reg.h"
#include "hmsppe/hppe_stp_reg.h"
#include "hmsppe/hppe_trunk_reg.h"
#include "hmsppe/hppe_vsi_reg.h"
#include "hmsppe/appe_acl_reg.h"
#include "hmsppe/appe_counter_reg.h"
#include "hmsppe/appe_geneve_reg.h"
#include "hmsppe/appe_global_reg.h"
#include "hmsppe/appe_l2_vp_reg.h"
#include "hmsppe/appe_policer_reg.h"
#include "hmsppe/appe_portvlan_reg.h"
#include "hmsppe/appe_pppoe_reg.h"
#include "hmsppe/appe_qm_reg.h"
#include "hmsppe/appe_sec_reg.h"
#include "hmsppe/appe_servcode_reg.h"
#include "hmsppe/appe_shaper_reg.h"
#include "hmsppe/appe_tunnel_map_reg.h"
#include "hmsppe/appe_tunnel_program_reg.h"
#include "hmsppe/appe_tunnel_reg.h"
#include "hmsppe/appe_vsi_reg.h"
#include "hmsppe/appe_vxlan_reg.h"
#include "hmsppe/mppe_athtag_reg.h"
#include "hmsppe/mppe_servcode_reg.h"
#include "hmsppe/mrppe_pktedit_reg.h"
#include "hmsppe/appe_qos_reg.h"
#include "hmsppe/jhppe_counter_reg.h"
#include "hmsppe/jhppe_ctrlpkt_reg.h"
#include "hmsppe/jhppe_pm_reg.h"
#include "hmsppe/jhppe_l2_vp_reg.h"
#include "hmsppe/jhppe_l3_flow_reg.h"
#include "hmsppe/jhppe_policer_reg.h"
#include "hmsppe/jhppe_portvlan_reg.h"
#include "hmsppe/jhppe_qm_reg.h"
#include "hmsppe/jhppe_servcode_reg.h"
#include "hmsppe/jhppe_tunnel_program_reg.h"
#include "hmsppe/jhppe_tunnel_reg.h"
#include "hmsppe/jhppe_pktedit_reg.h"
#include "hmsppe/jhppe_acl_reg.h"
#include "hmsppe/jhppe_loopback_reg.h"
#include "hmsppe/jhppe_athtag_reg.h"
#include "hmsppe/jhppe_ptp_reg.h"
#include "hmsppe/hmsppe_prx_pon_reg.h"

#include "hmsppe/hmsppe_prx_pon_api.h"
#include "hmsppe/appe_acl_api.h"
#include "hmsppe/appe_counter_api.h"
#include "hmsppe/appe_geneve_api.h"
#include "hmsppe/appe_global_api.h"
#include "hmsppe/appe_l2_vp_api.h"
#include "hmsppe/appe_policer_api.h"
#include "hmsppe/appe_portvlan_api.h"
#include "hmsppe/appe_pppoe_api.h"
#include "hmsppe/appe_qm_api.h"
#include "hmsppe/appe_sec_api.h"
#include "hmsppe/appe_servcode_api.h"
#include "hmsppe/appe_shaper_api.h"
#include "hmsppe/appe_tunnel_api.h"
#include "hmsppe/appe_tunnel_map_api.h"
#include "hmsppe/appe_tunnel_program_api.h"
#include "hmsppe/appe_vsi_api.h"
#include "hmsppe/appe_vxlan_api.h"
#include "hmsppe/appe_qos_api.h"
#include "hmsppe/hppe_acl_api.h"
#include "hmsppe/hppe_bm_api.h"
#include "hmsppe/hppe_ctrlpkt_api.h"
#include "hmsppe/hppe_fdb_api.h"
#include "hmsppe/hppe_flow_api.h"
#include "hmsppe/hppe_ip_api.h"
#include "hmsppe/hppe_mib_api.h"
#include "hmsppe/hppe_mirror_api.h"
#include "hmsppe/hppe_policer_api.h"
#include "hmsppe/hppe_portctrl_api.h"
#include "hmsppe/hppe_portvlan_api.h"
#include "hmsppe/hppe_qm_api.h"
#include "hmsppe/hppe_qos_api.h"
#include "hmsppe/hppe_rss_api.h"
#include "hmsppe/hppe_sec_api.h"
#include "hmsppe/hppe_servcode_api.h"
#include "hmsppe/hppe_shaper_api.h"
#include "hmsppe/hppe_stp_api.h"
#include "hmsppe/hppe_trunk_api.h"
#include "hmsppe/hppe_vsi_api.h"
#include "hmsppe/jhppe_acl_api.h"
#include "hmsppe/jhppe_counter_api.h"
#include "hmsppe/jhppe_ctrlpkt_api.h"
#include "hmsppe/jhppe_pm_api.h"
#include "hmsppe/jhppe_l2_vp_api.h"
#include "hmsppe/jhppe_l3_flow_api.h"
#include "hmsppe/jhppe_pktedit_api.h"
#include "hmsppe/jhppe_policer_api.h"
#include "hmsppe/jhppe_portvlan_api.h"
#include "hmsppe/jhppe_qm_api.h"
#include "hmsppe/jhppe_servcode_api.h"
#include "hmsppe/jhppe_tunnel_api.h"
#include "hmsppe/jhppe_tunnel_program_api.h"
#include "hmsppe/jhppe_loopback_api.h"
#include "hmsppe/jhppe_athtag_api.h"
#include "hmsppe/jhppe_ptp_api.h"
#include "hmsppe/mppe_athtag_api.h"
#include "hmsppe/mppe_servcode_api.h"
#include "hmsppe/mrppe_pktedit_api.h"


sw_error_t hppe_reg_get(a_uint32_t dev_id, a_uint32_t reg_addr, a_uint32_t *val);
sw_error_t hppe_reg_set(a_uint32_t dev_id, a_uint32_t reg_addr, a_uint32_t val);
sw_error_t hppe_reg_tbl_get(a_uint32_t dev_id, a_uint32_t reg_addr, a_uint32_t *val, a_uint32_t num);
sw_error_t hppe_reg_tbl_set(a_uint32_t dev_id, a_uint32_t reg_addr, a_uint32_t *val, a_uint32_t num);

//to be fixed
#include "hmsppe/hsl_misc.h"
