/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: ISC
 */

/**
 * @defgroup fal_pon_pm FAL_PON_PM
 * @{
 */
#ifndef _FAL_PON_PM_H_
#define _FAL_PON_PM_H_

#ifdef __cplusplus
extern "C" {
#endif                          /* __cplusplus */

#include "sw.h"
#include "fal_type.h"

typedef struct
{
	fal_pbmp_t port_id; /* port id includeing port bitmap, port/vp, vp group, gem port */
	a_uint8_t vlan_tag_fmt; /* 0x1(BIT0) untagged, 0x2(BIT1) pri-tagged, 0x4(BIT2) tagged */
	a_bool_t vlan_id_valid; /* check if rule will include VLAN ID */
	a_uint16_t vlan_id; /* VLAN ID value */
	a_bool_t vlan_pcp_valid; /* check if rule will include VLAN PCP */
	a_uint8_t vlan_pcp; /* VLAN PCP value */
	a_uint8_t ipmc_type; /* 0x1(BIT0) non ipmc, 0x2(BIT1) ipv4 mc, 0x4(BIT2) ipv6 mc */
	a_uint8_t counter_id; /* For ingress, the counter ID is generated by the counter entry;
			       * For egress, the counter ID is the counter entry index.
			       */
} fal_pon_pm_counter_entry_t;

typedef struct
{
	a_uint64_t packets_ucast; /* unicast packet counter */
	a_uint64_t packets_bcast; /* broadcast packet counter */
	a_uint64_t packets_mcast; /* multicast packet counter */
	a_uint64_t packets_oversize; /* oversize packet counter */
	a_uint64_t bytes; /* total bytes counter */
	a_uint64_t crc_errors; /* crc error counter */
	a_uint64_t packets_64octets; /* 64octets packet counter */
	a_uint64_t packets_65to127octets; /* 65to127octets packet counter */
	a_uint64_t packets_128to255octets; /* 128to255octets packet counter */
	a_uint64_t packets_256to511octets; /* 256to511octets packet counter */
	a_uint64_t packets_512to1023octets; /* 512to1023octets packet counter */
	a_uint64_t packets_1024to1518octets; /* 1024to1518octets packet counter */
} fal_pon_pm_counter_t;

sw_error_t
fal_pon_pm_counter_entry_set(a_uint32_t dev_id, a_uint32_t entry_index,
		fal_direction_t direction, fal_pon_pm_counter_entry_t *entry);
sw_error_t
fal_pon_pm_counter_entry_get(a_uint32_t dev_id, a_uint32_t entry_index,
		fal_direction_t direction, fal_pon_pm_counter_entry_t *entry);
sw_error_t
fal_pon_pm_counter_get(a_uint32_t dev_id, a_uint32_t counter_id,
		fal_direction_t direction, fal_pon_pm_counter_t *pm_counter);
sw_error_t
fal_pon_pm_counter_flush(a_uint32_t dev_id, a_uint32_t counter_id,
		fal_direction_t direction);
#ifdef __cplusplus
}
#endif                          /* __cplusplus */
#endif                          /* _FAL_PON_PM_H_ */
/**
 * @}
 */
