/*
* Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
* SPDX-License-Identifier: ISC
*/

/**
 * @defgroup
 * @{
 */
#include "sw.h"
#include "hsl_reg.h"
#include "fal_pon_pm.h"
#include "adpt.h"

sw_error_t
adpt_jhppe_pon_pm_counter_entry_set(a_uint32_t dev_id, a_uint32_t entry_index,
		fal_direction_t direction, fal_pon_pm_counter_entry_t *entry)
{
	sw_error_t rv;

	if (direction == FAL_DIR_INGRESS || direction == FAL_DIR_BOTH) {
		union pre_ipo_pm_counter_gen_u counter_gen = {0};
		counter_gen.bf.tag_fmt = entry->vlan_tag_fmt;
		counter_gen.bf.vid_incl = entry->vlan_id_valid;
		counter_gen.bf.vid = entry->vlan_id;
		counter_gen.bf.pcp_incl = entry->vlan_pcp_valid;
		counter_gen.bf.pcp = entry->vlan_pcp;
		counter_gen.bf.ipmc = entry->ipmc_type;
		counter_gen.bf.counter_id = entry->counter_id;
		/* convert port type and port id */
		counter_gen.bf.port_type = adpt_port_type_convert(A_TRUE,
				FAL_PORT_ID_TYPE(entry->port_id));
		counter_gen.bf.port = FAL_PORT_ID_VALUE(entry->port_id);
		rv = jhppe_pre_ipo_pm_counter_gen_set(dev_id, entry_index, &counter_gen);
		SW_RTN_ON_ERROR(rv);
	}

	if (direction == FAL_DIR_EGRESS || direction == FAL_DIR_BOTH) {
		union eg_pm_counter_gen_u eg_counter_gen = {0};
		eg_counter_gen.bf.tag_fmt = entry->vlan_tag_fmt;
		eg_counter_gen.bf.vid_incl = entry->vlan_id_valid;
		eg_counter_gen.bf.vid = entry->vlan_id;
		eg_counter_gen.bf.pcp_incl = entry->vlan_pcp_valid;
		eg_counter_gen.bf.pcp = entry->vlan_pcp;
		eg_counter_gen.bf.ipmc_0 = entry->ipmc_type;
		eg_counter_gen.bf.ipmc_1 = entry->ipmc_type >>
			SW_FIELD_OFFSET_IN_WORD(EG_PM_COUNTER_GEN_IPMC_OFFSET);
		/* convert port type and port id */
		eg_counter_gen.bf.port_type = adpt_port_type_convert(A_TRUE,
				FAL_PORT_ID_TYPE(entry->port_id));
		eg_counter_gen.bf.port = FAL_PORT_ID_VALUE(entry->port_id);
		/* for egress, counter id is the counter entry index, if input counter
		 * id is not equal with entry index, overwrite it as entry index.
		 */
		entry->counter_id = entry_index;
		rv = jhppe_eg_pm_counter_gen_set(dev_id, entry_index, &eg_counter_gen);
		SW_RTN_ON_ERROR(rv);
	}

	return SW_OK;
}

sw_error_t
adpt_jhppe_pon_pm_counter_entry_get(a_uint32_t dev_id, a_uint32_t entry_index,
		fal_direction_t direction, fal_pon_pm_counter_entry_t *entry)
{
	sw_error_t rv;

	if (direction == FAL_DIR_INGRESS) {
		union pre_ipo_pm_counter_gen_u counter_gen = {0};
		rv = jhppe_pre_ipo_pm_counter_gen_get(dev_id, entry_index, &counter_gen);
		SW_RTN_ON_ERROR(rv);
		entry->vlan_tag_fmt = counter_gen.bf.tag_fmt;
		entry->vlan_id_valid = counter_gen.bf.vid_incl;
		entry->vlan_id = counter_gen.bf.vid;
		entry->vlan_pcp_valid = counter_gen.bf.pcp_incl;
		entry->vlan_pcp = counter_gen.bf.pcp;
		entry->ipmc_type = counter_gen.bf.ipmc;
		/* for ingress, counter id is generated by counter entry */
		entry->counter_id = counter_gen.bf.counter_id;
		/* convert port type and port id */
		entry->port_id = FAL_PORT_ID(adpt_port_type_convert(A_FALSE,
					counter_gen.bf.port_type), counter_gen.bf.port);
	} else if (direction == FAL_DIR_EGRESS) {
		union eg_pm_counter_gen_u eg_counter_gen = {0};
		rv = jhppe_eg_pm_counter_gen_get(dev_id, entry_index, &eg_counter_gen);
		SW_RTN_ON_ERROR(rv);
		entry->vlan_tag_fmt = eg_counter_gen.bf.tag_fmt;
		entry->vlan_id_valid = eg_counter_gen.bf.vid_incl;
		entry->vlan_id = eg_counter_gen.bf.vid;
		entry->vlan_pcp_valid = eg_counter_gen.bf.pcp_incl;
		entry->vlan_pcp = eg_counter_gen.bf.pcp;
		entry->ipmc_type = (eg_counter_gen.bf.ipmc_1 <<
				SW_FIELD_OFFSET_IN_WORD(EG_PM_COUNTER_GEN_IPMC_OFFSET)) |
				eg_counter_gen.bf.ipmc_0;
		/* convert port type and port id */
		entry->port_id = FAL_PORT_ID(adpt_port_type_convert(A_FALSE,
					eg_counter_gen.bf.port_type), eg_counter_gen.bf.port);
		/* for egress, counter id is the entry index */
		entry->counter_id = entry_index;
	} else {
		return SW_NOT_SUPPORTED;
	}

	return SW_OK;
}

sw_error_t
adpt_jhppe_pon_pm_counter_get(a_uint32_t dev_id, a_uint32_t counter_id,
		fal_direction_t direction, fal_pon_pm_counter_t * pm_counter)
{
	sw_error_t rv;

	if (direction == FAL_DIR_INGRESS) {
		union pm_counter_tbl_u pm_cnt = {0};
		rv = jhppe_pm_counter_tbl_get(dev_id, counter_id, &pm_cnt);
		SW_RTN_ON_ERROR(rv);

		pm_counter->bytes = (a_uint64_t)pm_cnt.bf.octets_1 << 32 |
					(a_uint64_t)pm_cnt.bf.octets_0;
		pm_counter->packets_ucast = pm_cnt.bf.ucast_packet_1 << 24 |
					pm_cnt.bf.ucast_packet_0;
		pm_counter->packets_bcast = pm_cnt.bf.bcast_packet_1 << 24 |
					pm_cnt.bf.bcast_packet_0;
		pm_counter->packets_mcast = pm_cnt.bf.mcast_packet_1 << 24 |
					pm_cnt.bf.mcast_packet_0;
		pm_counter->crc_errors = pm_cnt.bf.crc_error_1 << 24 | pm_cnt.bf.crc_error_0;
		pm_counter->packets_oversize = pm_cnt.bf.oversize_1 << 24 | pm_cnt.bf.oversize_0;
		pm_counter->packets_64octets = pm_cnt.bf.frame_64_1 << 24 | pm_cnt.bf.frame_64_0;
		pm_counter->packets_65to127octets = pm_cnt.bf.frame_65_127_1 << 24 |
					pm_cnt.bf.frame_65_127_0;
		pm_counter->packets_128to255octets = pm_cnt.bf.frame_128_255_1 << 24 |
					pm_cnt.bf.frame_128_255_0;
		pm_counter->packets_256to511octets = pm_cnt.bf.frame_256_511_1 << 24 |
					pm_cnt.bf.frame_256_511_0;
		pm_counter->packets_512to1023octets = pm_cnt.bf.frame_512_1023_1 << 24 |
					pm_cnt.bf.frame_512_1023_0;
		pm_counter->packets_1024to1518octets = pm_cnt.bf.frame_1024_1518_1 << 24 |
					pm_cnt.bf.frame_1024_1518_0;
	} else if (direction == FAL_DIR_EGRESS) {
		union eg_pm_counter_tbl_u  eg_pm_cnt = {0};
		rv = jhppe_eg_pm_counter_tbl_get(dev_id, counter_id, &eg_pm_cnt);
		SW_RTN_ON_ERROR(rv);

		pm_counter->bytes = (a_uint64_t)eg_pm_cnt.bf.octets_1 << 32 |
					(a_uint64_t)eg_pm_cnt.bf.octets_0;
		pm_counter->packets_ucast = eg_pm_cnt.bf.ucast_packet_1 << 24 |
					eg_pm_cnt.bf.ucast_packet_0;
		pm_counter->packets_bcast = eg_pm_cnt.bf.bcast_packet_1 << 24 |
					eg_pm_cnt.bf.bcast_packet_0;
		pm_counter->packets_mcast = eg_pm_cnt.bf.mcast_packet_1 << 24 |
					eg_pm_cnt.bf.mcast_packet_0;
		pm_counter->packets_oversize = eg_pm_cnt.bf.oversize_1 << 24 |
					eg_pm_cnt.bf.oversize_0;
		pm_counter->packets_64octets = eg_pm_cnt.bf.frame_64_1 << 24 |
					eg_pm_cnt.bf.frame_64_0;
		pm_counter->packets_65to127octets = eg_pm_cnt.bf.frame_65_127_1 << 24 |
					eg_pm_cnt.bf.frame_65_127_0;
		pm_counter->packets_128to255octets = eg_pm_cnt.bf.frame_128_255_1 << 24 |
					eg_pm_cnt.bf.frame_128_255_0;
		pm_counter->packets_256to511octets = eg_pm_cnt.bf.frame_256_511_1 << 24 |
					eg_pm_cnt.bf.frame_256_511_0;
		pm_counter->packets_512to1023octets = eg_pm_cnt.bf.frame_512_1023_1 << 24 |
					eg_pm_cnt.bf.frame_512_1023_0;
		pm_counter->packets_1024to1518octets = eg_pm_cnt.bf.frame_1024_1518_1 << 24 |
					eg_pm_cnt.bf.frame_1024_1518_0;
	} else {
		return SW_NOT_SUPPORTED;
	}

	return SW_OK;
}

sw_error_t
adpt_jhppe_pon_pm_counter_flush(a_uint32_t dev_id, a_uint32_t counter_id,
		fal_direction_t direction)
{
	sw_error_t rv;

	if (direction == FAL_DIR_INGRESS || direction == FAL_DIR_BOTH) {
		union pm_counter_tbl_u pm_cnt = {0};
		rv = jhppe_pm_counter_tbl_set(dev_id, counter_id, &pm_cnt);
		SW_RTN_ON_ERROR(rv);
	}

	if (direction == FAL_DIR_EGRESS || direction == FAL_DIR_BOTH) {
		union eg_pm_counter_tbl_u  eg_pm_cnt = {0};
		rv = jhppe_eg_pm_counter_tbl_set(dev_id, counter_id, &eg_pm_cnt);
		SW_RTN_ON_ERROR(rv);
	}

	return SW_OK;
}

sw_error_t adpt_jhppe_pon_pm_init(a_uint32_t dev_id)
{
	adpt_api_t *p_adpt_api = NULL;

	p_adpt_api = adpt_api_ptr_get(dev_id);
	ADPT_NULL_POINT_CHECK(p_adpt_api);

	p_adpt_api->adpt_pon_pm_counter_entry_set = adpt_jhppe_pon_pm_counter_entry_set;
	p_adpt_api->adpt_pon_pm_counter_entry_get = adpt_jhppe_pon_pm_counter_entry_get;
	p_adpt_api->adpt_pon_pm_counter_get = adpt_jhppe_pon_pm_counter_get;
	p_adpt_api->adpt_pon_pm_counter_flush = adpt_jhppe_pon_pm_counter_flush;

	return SW_OK;
}

/**
 * @}
 */
